feat: function claim_rewards for claiming DeFi Spring rewards
djeck1432/spotnet pull request #118
Opened 2024-10-26 15:23 UTC by SoarinSkySagar

closes #102 

 - [x] Created ClaimData struct
 - [x] Written `claim_rewards` function
   - [x] Checking if position is open
   - [x] Claim all rewards one by one and transfer them to some address
 - [ ] Written test for `claim_rewards`

2024-10-28 17:29 UTC, faurdent requested changes
Some small changes required, mostly looks good

2024-10-28 17:29 UTC, faurdent commented on src/deposit.cairo
> +            let airdrop_addr: ContractAddress =
It was not by the start, but every week zkLend deploys a new contract and rewards might go there. Please, make this a parameter of `claim_rewards` method so it won't be constant.

2024-10-28 17:29 UTC, faurdent commented on src/interfaces.cairo
> +pub trait IAirdrop<TContractState> {
Remove all unused methods from interface as they go in the line count for audit. Always try to keep as little code as possible.

2024-10-28 17:29 UTC, faurdent commented on src/types.cairo
> +pub struct Config {
After a part of methods from `IAirdrop` is removed this one gonna be unneeded too.

2024-10-28 17:29 UTC, faurdent commented on src/deposit.cairo
> +            assert(res, 'Claim failed');
When event removed make a one-liner.

2024-10-28 17:29 UTC, faurdent commented on tests/test_loop.cairo
> +    deposit_disp.claim_rewards(claim_data: claim_data, proofs: proofs);
I think names are descriptive, why not to pass them as is

2024-10-28 20:43 UTC, faurdent approved these changes
@djeck1432 LGTM, approved

2024-10-29 09:01 UTC, djeck1432 approved these changes
Looks good to me

2024-10-29 09:02 UTC, merged

2024-10-29 17:04 UTC, SoarinSkySagar commented
thank you @djeck1432 and @faurdent, would love to contribute to spotnet again 🚀