Fetch data from /api/get_stats and display in frontend
djeck1432/spotnet pull request #143
Opened 2024-10-29 20:07 UTC by KevinLatino

Here you have an image: 
![image](https://github.com/user-attachments/assets/7dfaf4f0-70e1-4385-ab00-dd9dda6ce4e3)

2024-10-29 22:12 UTC, whateverfw requested changes

2024-10-29 22:12 UTC, whateverfw commented on frontend/src/pages/spotnet/information/Informaion.jsx
fix misspelling in file name

2024-10-29 22:12 UTC, whateverfw commented on frontend/src/pages/spotnet/information/Informaion.jsx
> +                const response = await fetch(`${process.env.REACT_APP_BACKEND_URL}/api/get_stats`);
use axios instead of fetch

2024-10-29 22:12 UTC, whateverfw commented on frontend/src/pages/spotnet/information/Informaion.jsx
> +                    <Star
use https://github.com/djeck1432/spotnet/blob/main/frontend/src/components/StarMaker.jsx instead

2024-10-29 22:22 UTC, whateverfw requested changes

2024-10-29 22:22 UTC, whateverfw commented on frontend/src/pages/spotnet/information/Informaion.jsx
> +                    <h3>{loading ? "Loading..." : error ? `Error: ${error}` : data.total_opened_amount}</h3>
Value should be formatted into such style `$245.7k`. Currently it seems to just display raw number from a backend

2024-10-29 23:05 UTC, whateverfw approved these changes

2024-10-30 11:05 UTC, djeck1432 approved these changes
Looks good to me

2024-10-30 11:06 UTC, merged