adaptive Main page
djeck1432/spotnet pull request #162
Opened 2024-11-01 12:15 UTC by od-hunter

please review

2024-11-01 12:17 UTC, djeck1432 commented
@od-hunter Please resolve merge conflict

2024-11-02 04:25 UTC, whateverfw requested changes

2024-11-02 04:25 UTC, whateverfw commented on frontend/src/pages/spotnet/about/About.jsx
> +            ))}
Please use already existing `StarMaker` component instead

2024-11-02 04:25 UTC, whateverfw commented on frontend/src/pages/spotnet/about/About.jsx
this file cause build errors

could you please fix it and verify by doing `npm run build` locally?

src/pages/spotnet/about/About.jsx
16.40 Syntax error: Unexpected token, expected "," (75:8) (75:8)

2024-11-02 04:25 UTC, whateverfw commented on frontend/src/components/Footer/footer.css
> +
this seems to partially repeat functionality that already exists in `globals.css`, please combine missing parts into `globals.css` and remove this from `footer.css` and verify everything still works correctly

2024-11-02 04:25 UTC, whateverfw commented on frontend/src/pages/spotnet/home/home.css
> +}
this seems to partially repeat functionality that already exists in `globals.css`, please combine missing parts into `globals.css` and remove this from `home.css` and verify everything still works correctly

2024-11-02 07:54 UTC, whateverfw requested changes
Also please resolve merge conflicts with `main` using footer and header versions from there and verifying it works well along with your other changes

Thanks

2024-11-02 17:03 UTC, whateverfw commented
@od-hunter

2024-11-03 07:42 UTC, whateverfw requested changes
also fix build issues (check CI)

before you next commit please run `npm run build` and verify that nothing fails, thx

2024-11-03 07:42 UTC, whateverfw commented on frontend/src/components/header/Header.jsx
this wasn't merged properly, just keep Header component that is on main (also css)

2024-11-03 07:42 UTC, whateverfw commented on frontend/src/components/Footer/Footer.jsx
this wasn't merged properly, just keep Header component that is on main (also css)

2024-11-03 09:06 UTC, whateverfw approved these changes

2024-11-03 10:20 UTC, djeck1432 approved these changes
Looks good to me

2024-11-03 10:21 UTC, merged