feat: implement function to check health_ratio_level per wallet_id
djeck1432/spotnet pull request #200
Opened 2024-11-13 14:21 UTC by Akshola00

## Overview
cloese issue [#199]
This PR implements the `AlertMixin` class and its associated functionality to check the health ratio level of users with an OPENED position status. If a user's health ratio level is lower than the required threshold of `1.1`, a custom exception `HealthRatioLevelLowException` is raised. The following changes are included:

- **AlertMixin Class**: Added the `check_users_health_ratio_level` method, which:
  - Fetches all users with an OPENED position.
  - Retrieves the user's position using `DashboardMixin`.
  - Checks the user's health ratio level, raising the `HealthRatioLevelLowException` if the ratio is below `1.1`.
  
- **UserDBConnector Class**: Added the `get_all_users_with_opened_position` method, which fetches all users with an OPENED position status from the database.

- **Custom Exception**: Added `HealthRatioLevelLowException` to raise when a user's health ratio level is below `1.1`.

2024-11-13 14:31 UTC, djeck1432 requested changes

2024-11-13 14:31 UTC, djeck1432 commented on web_app/contract_tools/mixins/alert.py
> +class Status(Enum):
why did you created class if we have it already
https://github.com/djeck1432/spotnet/blob/main/web_app/db/models.py#L25

2024-11-13 14:31 UTC, djeck1432 commented on web_app/contract_tools/mixins/alert.py
> +class HealthRatioLevelLowException(Exception):
create separated file `custom_exception.py` and move it there

2024-11-13 14:31 UTC, djeck1432 commented on web_app/contract_tools/mixins/alert.py
> +                for position in user.positions:
user normally has only one `opened` position

2024-11-13 14:31 UTC, djeck1432 commented on web_app/contract_tools/mixins/alert.py
> +                    if position.status == Status.OPENED.value:
move this logic inside `crud` method, it shouldn't be here

2024-11-13 14:31 UTC, djeck1432 commented on web_app/contract_tools/mixins/alert.py
> +                for position in user.positions:
remove this `loop` you can go through just `user.contract_address`

2024-11-13 14:31 UTC, djeck1432 commented on web_app/db/crud.py
> +                    db.query(User)
Please, use `Position` and get from there all users. It will be definetly better way instead of having 2 joins

2024-11-13 14:31 UTC, djeck1432 commented on web_app/db/crud.py
> +    def get_all_users_with_opened_position(self) -> List[User]:
why this method here, if it should be in UserDBConnector?

2024-11-14 07:38 UTC, djeck1432 requested changes

2024-11-14 07:38 UTC, djeck1432 commented on web_app/contract_tools/mixins/alert.py
> +        if users:
why do you need it here, if any users were found it will return empty list, please remove it

2024-11-14 07:38 UTC, djeck1432 commented on web_app/contract_tools/mixins/alert.py
> +                if health_ratio_level < 1.1:
Move `1.1` to constant list `ALERT_THRESHOLD`

2024-11-14 07:38 UTC, djeck1432 commented on web_app/db/crud.py
> +            try:
WHy not just use one left and one request to db?
```
   users = (
                db.query(User)
                .join(Position, Position.user_id == User.id)
                .filter(Position.status == Status.OPENED.value)
                .distinct()
                .all()
            )
 ```

2024-11-14 10:08 UTC, djeck1432 commented
@Akshola00 Any update, if next 4-6 hours will not see changes, you will be unassigned

2024-11-14 10:10 UTC, Akshola00 commented
> @Akshola00 Any update, if next 4-6 hours will not see changes, you will be unassigned 

Currently working on it

2024-11-14 15:42 UTC, djeck1432 approved these changes
Looks good to me

2024-11-14 15:43 UTC, merged