feat: create endpoint to check if user has already opened position
djeck1432/spotnet pull request #212
Opened 2024-11-15 22:01 UTC by dahtee

## Add User Position Status Check Endpoint

### Changes Made
- Added new GET endpoint `/api/has-user-opened-position` to check user's position status
- Implemented CRUD method `has_opened_position` in PositionDBConnector
- Added boolean response for position status check

### Technical Details
- New endpoint accepts `wallet_id` as input parameter
- Returns simple boolean response: `true` if user has opened position, `false` otherwise
- Implements proper error handling for database queries

### Related Issue
Closes [#210]

2024-11-16 13:25 UTC, dahtee commented
Hello @djeck1432 kindly review.

2024-11-17 10:24 UTC, djeck1432 requested changes

2024-11-17 10:24 UTC, djeck1432 commented on web_app/api/user.py
> +            status_code=500,
500 error related to server error, 
it should be 4** status response

2024-11-17 10:24 UTC, djeck1432 commented on web_app/api/user.py
> +    except Exception as e:
Please, be more specific with exception, try to avoid using generic one

2024-11-17 10:24 UTC, djeck1432 commented on web_app/db/crud.py
> +                position_exists = (
Please, use already exisiting method `exists`

```
position_exists = db.query(
    db.query(Position)
    .filter(
        Position.user_id == user.id,
        Position.status == Status.OPENED.value,
    )
    .exists()
).scalar()
```

2024-11-17 20:16 UTC, dahtee commented
On it now Sir.

2024-11-18 09:07 UTC, djeck1432 commented
@dahtee Please, fix pylint issue

2024-11-18 09:13 UTC, djeck1432 approved these changes
Looks good to me

2024-11-18 09:13 UTC, merged