Feat/add pop up window
djeck1432/spotnet pull request #220
Opened 2024-11-20 18:14 UTC by PoulavBhowmick03

Fixes #213

2024-11-21 18:30 UTC, whateverfw requested changes
please resolve merge conflict

2024-11-21 18:30 UTC, whateverfw commented on frontend/src/pages/forms/Form.jsx
> +  }, [walletId]);
api requests should be done using tanstack query library (that is already part of a project), also using axios, not fetch

2024-11-21 18:30 UTC, whateverfw commented on frontend/src/components/openpositionpopup/popup.css
use css variables for colors

2024-11-21 18:30 UTC, whateverfw commented on frontend/src/components/openpositionpopup/StyledPopup.jsx
> +/* eslint-disable react/no-unescaped-entities */
avoid disabling eslint, fix issues instead

2024-11-22 13:44 UTC, djeck1432 commented
@PoulavBhowmick03 Any updates?
please, sync with main

2024-11-22 14:38 UTC, PoulavBhowmick03 commented
Yes, give me 30 mins, updating the changes asked

2024-11-22 19:23 UTC, merged