feat: added modal to handle confirm logout
djeck1432/spotnet pull request #233
Opened 2024-11-21 17:29 UTC by Ayoazeez26

This PR fixes #223

2024-11-21 18:23 UTC, whateverfw requested changes

2024-11-21 18:23 UTC, whateverfw commented on frontend/src/components/Logout/logoutModal.css
> +}
seems like this clases is not relavant to logout modal

2024-11-21 18:23 UTC, whateverfw commented on frontend/src/components/Logout/logoutModal.css
> +  border: 1px solid rgba(54, 41, 78, 1);
use css variables if already exists, if not create new ones (check global.css and figma hex colors)

2024-11-21 18:23 UTC, whateverfw commented on frontend/src/components/Logout/logoutModal.css
> +  border-bottom: 1px solid #36294E;
use css variable

2024-11-21 18:23 UTC, whateverfw commented on frontend/src/components/Logout/logoutModal.css
> +  background: linear-gradient(73.48deg, #e01dee 1.13%, #49abd2 51.27%);
use css variable

2024-11-21 18:23 UTC, whateverfw commented on frontend/src/components/Logout/logoutModal.css
> +  background: linear-gradient(90deg, #74D6FD 0%, #E01DEE 100%);
use css variable

2024-11-21 18:23 UTC, whateverfw commented on frontend/src/components/Logout/logoutModal.css
> +  background: linear-gradient(73.48deg, #e01dee 1.13%, #49abd2 51.27%);
use css variables

2024-11-21 18:23 UTC, whateverfw commented on frontend/src/components/Logout/LogoutModal.jsx
> +          <button className="cancel-button" onClick={() => onClose()}>
can be just onClick={onClose}

2024-11-21 18:23 UTC, whateverfw commented on frontend/src/components/Logout/LogoutModal.jsx
> +            onClick={() => onLogout()}
onClick={onLogout}

2024-11-21 18:23 UTC, whateverfw commented on frontend/src/components/Logout/LogoutModal.jsx
> +  return (
remove redundant spacing

2024-11-21 18:23 UTC, whateverfw commented on frontend/src/App.jsx
> +    setShowModal(false);
use closeModal function that already has closing functionality

2024-11-22 00:24 UTC, Ayoazeez26 commented
Comments addressed @whateverfw

2024-11-22 10:11 UTC, whateverfw requested changes
![image](https://github.com/user-attachments/assets/2fc1dc6a-40a7-4284-b53a-f3de1f64a48b)
Cancel button has broken UI with squared corners, please fix

2024-11-22 13:43 UTC, djeck1432 commented
@Ayoazeez26 any updates?

2024-11-22 17:05 UTC, djeck1432 approved these changes
LGTM

2024-11-22 17:06 UTC, merged