feat: Draft PR For [FRONTEND] Form page (desktop) task
djeck1432/spotnet pull request #253
Opened 2024-11-23 17:05 UTC by DanielEmmanuel1

Form Page Rework (Desktop Version)

Changes made:

- Redesigned form page layout according to Figma designs for desktop view
- Enhanced UI components:
- Implemented new multiplier selector with dynamic gradient slider
- Updated token selector styling
- Improved balance cards display
- Refined form input fields and styling
- Maintained backend integration and functionality
- Preserved all existing form submission logic

2024-11-23 19:11 UTC, whateverfw requested changes
Please make sure that every part of the page is done according to figma, currently most of the styles don't match Figma

2024-11-23 19:11 UTC, whateverfw commented on frontend/src/components/BalanceCards.jsx
balance card styling doesn't match figma design

2024-11-23 19:11 UTC, whateverfw commented on frontend/src/components/MultiplierSelector.jsx
multiplier selector styles don't match figma

2024-11-23 19:11 UTC, whateverfw commented on frontend/src/components/TokenSelector.jsx
token selector' styles don't match figma

2024-11-23 19:11 UTC, whateverfw commented on frontend/src/components/BalanceCards.jsx
> -    { icon: <DAI />, title: 'DAI', balance: '0.00' },
keep previous icons

2024-11-23 19:11 UTC, whateverfw commented on frontend/src/pages/forms/Form.jsx
page background doesn't match figma

2024-11-24 08:34 UTC, whateverfw commented on frontend/src/pages/forms/Form.jsx
still unresolved

2024-11-24 08:35 UTC, whateverfw commented on frontend/src/components/TokenSelector.jsx
sizes still doesn't match figma

2024-11-24 08:35 UTC, whateverfw commented on frontend/src/components/MultiplierSelector.jsx
still not matching figma

2024-11-24 08:35 UTC, whateverfw commented on frontend/src/components/BalanceCards.jsx
still not matching figma

2024-11-24 08:36 UTC, whateverfw requested changes

2024-11-24 08:36 UTC, whateverfw commented on frontend/src/components/TokenSelector.jsx
> +  const [tokenSelect, setTokenSelect] = useState('STRK');
why do we have this state? we already have `selectedToken`

2024-11-24 08:37 UTC, DanielEmmanuel1 commented on frontend/src/pages/forms/Form.jsx
I literally got the background.png used in dashboard component, please can u point me to the specific background I should be using.
Ty

2024-11-24 08:56 UTC, whateverfw commented on frontend/src/components/TokenSelector.jsx
> +  const [tokenSelect, setTokenSelect] = useState('STRK');
but we already have `selectedToken` in `Form.jsx` that can be passed to `TokenSelector` component

2024-11-24 09:56 UTC, whateverfw commented on frontend/src/pages/forms/Form.jsx
I don't think it looks the same
![image](https://github.com/user-attachments/assets/61e2ce47-11b4-42b8-b225-e137e320ded0)
![image](https://github.com/user-attachments/assets/f9115dda-bed7-4f9c-81bd-e843a30c7669)

2024-11-24 11:07 UTC, djeck1432 commented
@DanielEmmanuel1 Any updates?

2024-11-24 11:52 UTC, DanielEmmanuel1 commented
> @DanielEmmanuel1 Any updates?

Yeah, I'm currently working on it right now

2024-11-24 16:05 UTC, DanielEmmanuel1 commented
@whateverfw Can u please go through it to confirm if its okay now

2024-11-24 16:29 UTC, whateverfw commented on frontend/src/components/TokenSelector.jsx
still doesn't match figma

2024-11-24 16:30 UTC, whateverfw commented on frontend/src/pages/forms/Form.jsx
overall now it is at least good direction, but you can clearly see that there are double stars in app, you should remove it.

2024-11-24 16:30 UTC, whateverfw commented on frontend/src/components/TokenSelector.jsx
> +  const [tokenSelect, setTokenSelect] = useState('STRK');
still unresolved after latest changes

2024-11-24 16:33 UTC, whateverfw commented
1) Background is more or less fixed, but not completely - double stars issue still persists
2) Token Selector items styles still don't match figma (different sizes)
3) You can clearly see that there are not margin from a top in Figma (above balance cards), but there is still in app
4) Issue with double state for selected token still unresolved

I've kept all unresolved threads active.

2024-11-24 16:38 UTC, whateverfw commented
Issues with select multiplier slider:
1) When 0x is selected there is no progress filled
![image](https://github.com/user-attachments/assets/54ba029e-0332-4d12-a767-f8735795640d)

2) With 1x or 3x values progress is not fully filled (there is some space before dot)
![image](https://github.com/user-attachments/assets/8c2c99df-d0f9-470c-98d2-513dc7fcc7c8)

3) I can't completely select 2x in a slider 

4) Dot is not exactly above multiplier label, it is shifted, e.g. it is not exactly on top of 3x
![image](https://github.com/user-attachments/assets/027de838-b75f-42fc-a6f9-2b44149b941b)

5) Seems like it is not filled with correct color, as in figma (e.g. you can clearly see that progress is blue, when 2x is selected), so progress gradient do not correspond to figma

6) In case of 10x dot should be in the end, as well as 10x label, so no progress on the right should be left
![image](https://github.com/user-attachments/assets/c0366e58-9761-473f-81d9-822f9b499124)

2024-11-24 16:39 UTC, whateverfw commented
Vertical margins are completely broken and do not correspond to figma:
App:
![image](https://github.com/user-attachments/assets/3266b145-5439-4216-8310-187ff9901835)
Figma: 
![image](https://github.com/user-attachments/assets/fc220c41-ede3-48f4-a897-a93744f37aa8)

2024-11-24 22:04 UTC, DanielEmmanuel1 commented
Done with majority of the issues
Working on the MultiplierSelector bugs

2024-11-25 17:23 UTC, DanielEmmanuel1 commented on frontend/src/components/MultiplierSelector.jsx
> max multiplier value should be dynamic, and depend on what is returned from useMaxMultiplier based on a selected token (currently it is always 10)

The issue progress background of blue been filled when at x0 mark, is not feasible cos with the new math calcs, the x10 mark is no longer been filled, so the approach is to just leave x0 as is.  As for the dynamic approach of the multiplier, i am getting a value of 2.5 from the backend and that wont work correctly to achieve the design.

2024-11-25 17:24 UTC, DanielEmmanuel1 commented on frontend/src/components/MultiplierSelector.jsx
> > max multiplier value should be dynamic, and depend on what is returned from useMaxMultiplier based on a selected token (currently it is always 10)
> 
> The issue progress background of blue been filled when at x0 mark, is not feasible cos with the new math calcs, the x10 mark is no longer been filled, so the approach is to just leave x0 as is. As for the dynamic approach of the multiplier, i am getting a value of 2.5 from the backend and that wont work correctly to achieve the design.

Maybe u can guide me on a better logic to achieve this

2024-11-25 18:07 UTC, whateverfw commented on frontend/src/components/MultiplierSelector.jsx
@DanielEmmanuel1 let's wait on this, I'll let you know

2024-11-25 18:17 UTC, whateverfw commented on frontend/src/components/MultiplierSelector.jsx
@DanielEmmanuel1 Okay, you don't need to make more changes. I'm considering that you've finished, thanks.

2024-11-25 18:18 UTC, whateverfw approved these changes
@DanielEmmanuel1 @djeck1432

2024-11-25 18:25 UTC, djeck1432 approved these changes
Looks good to me

2024-11-25 18:26 UTC, merged