Working on the Vault Group (Stake Page)
djeck1432/spotnet pull request #271
Opened 2024-11-26 09:28 UTC by nora360

2024-11-26 15:52 UTC, whateverfw requested changes

2024-11-26 15:52 UTC, whateverfw commented on frontend/src/pages/spotnet/Vault/Section.jsx
it seems like this component is not used and not needed at all

2024-11-26 15:52 UTC, whateverfw commented on frontend/src/pages/spotnet/Vault/TableOfContents.jsx
this is an exact copy of the component from a documentation page, can you instead move it to components folder and use the same component for documentation and here (passing correct items as props)

2024-11-26 18:07 UTC, djeck1432 commented
@nora360 Please, finish your PR and fix comments above

2024-11-26 18:28 UTC, whateverfw commented
@nora360 also, be sure to sync with main and resolve merge conflicts

2024-11-27 07:08 UTC, djeck1432 commented
@nora360 You were unassigned

2024-11-27 07:08 UTC, closed without merging