Added staking page feature
djeck1432/spotnet pull request #288
Opened 2024-11-27 20:05 UTC by chigozzdevv

Closes #265
![image](https://github.com/user-attachments/assets/5d272ff3-f30a-4346-b0ad-7ff39db75cc4)

I also imported the layout to the withdrawal page

![image](https://github.com/user-attachments/assets/9cd176e8-17f7-4aa9-bb16-3a6bc1a8db92)

2024-11-27 20:15 UTC, chigozzdevv commented
@djeck1432 please review

2024-11-27 20:19 UTC, whateverfw commented
@chigozzdevv fix failed CI PLS

2024-11-27 20:27 UTC, whateverfw requested changes

2024-11-27 20:27 UTC, whateverfw commented on frontend/src/pages/vault/VaultLayout.jsx
please do bg color of this side-layout as in figma, also you can see different paddings also differ

2024-11-27 20:27 UTC, whateverfw commented on frontend/src/pages/vault/stake/Stake.jsx
> +            <div className="network-dropdown">
![image](https://github.com/user-attachments/assets/1d7fedd4-1df5-4c1a-9d7e-7d95364b5e42)
can you please make it with rounded corners on option hover? currently it is squared

2024-11-27 20:27 UTC, whateverfw commented on frontend/src/pages/vault/stake/Stake.jsx
> +        <button className="stake-button">Stake</button>
Please use our generic `Button` component from `components/ui`

2024-11-27 20:27 UTC, whateverfw commented on frontend/src/pages/vault/stake/Stake.jsx
> +          <div className="balance-card">
please make sure these cards are done according to figma, currently there are some mismatches in aligning with icons and font sizes

2024-11-27 20:27 UTC, whateverfw commented on frontend/src/pages/vault/VaultLayout.jsx
make sure to highligh active page just like in Figma

2024-11-27 20:27 UTC, whateverfw commented on frontend/src/pages/vault/stake/Stake.jsx
> +            <div className="gas-icon">
this icon differs from figma, can you make a shared component with withdraw and use the same icon used there?

2024-11-27 20:27 UTC, whateverfw commented on frontend/src/pages/vault/stake/Stake.jsx
> +            </div>
you can create a shared component and use it here and on the withdraw page as it is the same

2024-11-27 20:27 UTC, whateverfw commented on frontend/src/pages/vault/stake/Stake.jsx
> +            <input type="text" defaultValue="0.00" className="amount-field" />
![image](https://github.com/user-attachments/assets/8b23f8a1-eb98-4797-ae92-061746b25385)
such thing can happen if I start writing a lot of numbers, part of the layout will be cut and everything will be shifted

2024-11-27 20:27 UTC, whateverfw commented on frontend/src/App.jsx
> +import { Notifier } from 'components/Notifier/Notifier';
this is already imported above

2024-11-27 21:48 UTC, whateverfw requested changes

2024-11-27 21:48 UTC, whateverfw commented on frontend/src/pages/vault/stake/Stake.jsx
> +          <div className="balance-card">
please use different name, not `balance-card` it conflicts with some items on other pages, and we'll deal with it later. for now just name it differently

2024-11-28 14:32 UTC, whateverfw commented on frontend/src/pages/vault/stake/Stake.jsx
> +          <div className="balance-card">
still undersolved

2024-11-28 14:33 UTC, whateverfw commented on frontend/src/pages/vault/VaultLayout.jsx
still unresolved

2024-11-28 14:33 UTC, whateverfw commented on frontend/src/pages/vault/stake/Stake.jsx
> +            <div className="gas-icon">
still unresolved

2024-11-28 14:34 UTC, whateverfw commented on frontend/src/pages/vault/stake/Stake.jsx
> +          <div className="balance-card">
still unresolved

2024-11-28 16:58 UTC, whateverfw requested changes

2024-11-28 16:58 UTC, whateverfw commented on frontend/src/components/StakeCard/GasFee.jsx
this file should be in own folder, not inside StakeCard, also it should have its own css file with proper names, and not the ones from withdraw.css

2024-11-28 16:58 UTC, whateverfw commented on frontend/src/pages/vault/stake/Stake.jsx
please make top margins according to figma, currently gap is smaller

2024-11-28 16:58 UTC, whateverfw commented on frontend/src/pages/vault/stake/stake.css
remove commented code, also use css variables (from global.css for colors)

2024-11-28 21:16 UTC, djeck1432 commented
@chigozzdevv any updates?

2024-11-28 21:21 UTC, chigozzdevv commented
> @chigozzdevv any updates?

Resolved sir

2024-11-28 21:22 UTC, chigozzdevv commented
I'm still working to resolve the latest issues. So sorry for the delay @djeck1432 🙏. It'll be up soon.

2024-11-28 21:23 UTC, whateverfw commented
@chigozzdevv so, did you resolve everything and I can check or it is still WIP?

2024-11-28 21:24 UTC, chigozzdevv commented
> did you resolve everything and I can

Please check I resolved everything you asked of

2024-11-28 21:28 UTC, whateverfw approved these changes
@chigozzdevv @djeck1432 LGTM

2024-11-28 21:32 UTC, merged