Worked on the withdraw page mobile responsive
djeck1432/spotnet pull request #299
Opened 2024-11-28 12:28 UTC by nora360

Closes #295

2024-11-28 14:48 UTC, whateverfw requested changes
![image](https://github.com/user-attachments/assets/e76f9e50-cb34-4d17-9d82-af3c580159f0)
Please check screen from 768px and below, currently it is broken and don't correspond to Figma. On some screens like above - everything goes outside a sceeen.

Card styles/padding don't correspond to Figma. Also you can clearly see that 2 cards should fit 1 row on a mobile, but currently it breaks into two lines

Please, go through figma and fix everything accordingly

2024-11-28 17:14 UTC, whateverfw commented
top cards don't correspond to figma's sizes
cards in the center have different border radius in figma
<img width="401" alt="image" src="https://github.com/user-attachments/assets/0981c06e-00a9-4949-a975-d6af31bfe9e5">
@nora360

2024-11-28 17:14 UTC, whateverfw requested changes
⏫  @nora360

2024-11-28 17:23 UTC, nora360 commented
@whateverfw  ok working on it

2024-11-28 18:48 UTC, whateverfw commented on frontend/src/components/MetricCard/metricCard.css
> +  /* For screens smaller than 1024px */
remove comments

2024-11-28 18:48 UTC, whateverfw commented on frontend/src/components/MetricCard/metricCard.css
> +    border-radius: 16px !important;
avoid important

2024-11-28 21:20 UTC, whateverfw commented
@nora360 any updates?

2024-11-29 06:45 UTC, whateverfw requested changes
@nora360 
<img width="1443" alt="image" src="https://github.com/user-attachments/assets/a369fd42-d88b-499e-be04-e3eb30ba147f">

desktop page is broken now as well, can you please make fixes that works both on mobile and desktop, so desktop looks like in Figma as well?

2024-11-29 06:46 UTC, whateverfw requested changes
<img width="385" alt="image" src="https://github.com/user-attachments/assets/a0fe6a07-bf22-493a-9f22-c0684751dfcb">
I don't know what is this, but it should be removed, appear on mobile screens at the bottom of a page

2024-11-29 06:49 UTC, whateverfw requested changes
I can clearly see a lot of mismatches with figma on mobile screens
That is Figma:
<img width="312" alt="image" src="https://github.com/user-attachments/assets/815a0c5a-701c-4401-b951-e07fc168f1de">
And that's broken app:
<img width="386" alt="image" src="https://github.com/user-attachments/assets/abb0fda7-a5b8-458a-ac04-bbd6052c9712">

Huge problems and mismatches with padding everywhere, please fix

2024-11-29 14:09 UTC, djeck1432 commented
@nora360 unassigned you, bad communication ,15 hours ago commited not finished work

2024-11-29 14:09 UTC, closed without merging