Rework slider on a Form page
djeck1432/spotnet pull request #302
Opened 2024-11-28 17:40 UTC by Thibrac

### Changes

ece3b0f11947cb26aa7b4864e3191fd7782398f4 : 
- Slider moving from 0.1 by 0.1
- Precise current multiplier displayed above cursor

2024-11-28 18:55 UTC, whateverfw requested changes
@Thibrac can you please also change condition in `Form.jsx` 48 line ` if (!positionData?.has_opened_position) {` to be `if (positionData?.has_opened_position)`

2024-11-28 18:55 UTC, whateverfw commented on frontend/src/components/MultiplierSelector.jsx
> +  const maxMultiplier = useMemo(() => 10, [data, selectedToken]);
it should be not hardcoded to 10, rather it should be equal to a value returned from a backend

2024-11-28 18:55 UTC, whateverfw commented on frontend/src/components/multiplier.css
there is not blue tooltip like in figma, please fix

2024-11-28 18:56 UTC, whateverfw requested changes

2024-11-28 18:56 UTC, whateverfw commented on frontend/src/components/multiplier.css
point css is not equal to figma's

2024-11-28 19:06 UTC, whateverfw requested changes
Slider thickness is incorrect on mobile screens, as well as horizontal and vertical margins. 
Please do exactly like in Figma

2024-11-28 21:02 UTC, whateverfw commented
@Thibrac Just in case: css is not fixed in last commit

2024-11-28 21:38 UTC, whateverfw commented
@Thibrac I don't think it will pass in front of "Select multiplier" if you do everything according to Figma, because there is padding from top
![image](https://github.com/user-attachments/assets/ac9d71f9-dfbb-4c21-abae-3425784d6989)

2024-11-29 06:23 UTC, whateverfw commented on frontend/src/components/multiplier.css
there is no triangle at the bottom of a tooltip

2024-11-29 06:23 UTC, whateverfw commented on frontend/src/components/multiplier.css
still don't correspond to figma

2024-11-29 06:25 UTC, whateverfw requested changes

2024-11-29 06:25 UTC, whateverfw commented on frontend/src/components/multiplier.css
Slider thickness is incorrect on mobile screens, as well as horizontal and vertical margins.
Please do exactly like in Figma

2024-11-29 06:25 UTC, whateverfw commented on frontend/src/components/multiplier.css
slider horizonal margins are not as in figma

2024-11-29 06:25 UTC, whateverfw commented on frontend/src/components/multiplier.css
slider bottom padding are not as in figma on **mobile**

2024-11-29 08:18 UTC, Thibrac commented on frontend/src/components/multiplier.css
wip

2024-11-29 09:36 UTC, whateverfw commented
@Thibrac tooltip is not the same as in figma

2024-11-29 09:45 UTC, whateverfw commented
> > @Thibrac Please test before you commit and request review next time:
> > broken tooltip and padding didn't change ![image](https://private-user-images.githubusercontent.com/40571528/391037374-658fc52e-6ca4-4808-a6c7-f23a850bf31c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NzM1NDEsIm5iZiI6MTczMjg3MzI0MSwicGF0aCI6Ii80MDU3MTUyOC8zOTEwMzczNzQtNjU4ZmM1MmUtNmNhNC00ODA4LWE2YzctZjIzYTg1MGJmMzFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDA5NDA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyMWRmNmQ0ZjY0ZjM0MmQ1N2UxZTc1MzViNWViZmI5YzcxNDc3NGZhM2VkZmI2MjBiYmU1MWYxYjFmNTNhOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bGkJr7U56-xwGftdgj4VBLaUtuN-STcxytOQzNRW0mc)
> 
> Sorry, I've done some tests, on which mobile is this bug? I don't have it..

Just try to make your screen size smaller in browser, it happend for me for the screens less than 500px or smth

2024-11-29 10:12 UTC, Thibrac commented
> > > @Thibrac Please test before you commit and request review next time:
> > > broken tooltip and padding didn't change ![image](https://private-user-images.githubusercontent.com/40571528/391037374-658fc52e-6ca4-4808-a6c7-f23a850bf31c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NzM1NDEsIm5iZiI6MTczMjg3MzI0MSwicGF0aCI6Ii80MDU3MTUyOC8zOTEwMzczNzQtNjU4ZmM1MmUtNmNhNC00ODA4LWE2YzctZjIzYTg1MGJmMzFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDA5NDA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyMWRmNmQ0ZjY0ZjM0MmQ1N2UxZTc1MzViNWViZmI5YzcxNDc3NGZhM2VkZmI2MjBiYmU1MWYxYjFmNTNhOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bGkJr7U56-xwGftdgj4VBLaUtuN-STcxytOQzNRW0mc)
> > 
> > 
> > Sorry, I've done some tests, on which mobile is this bug? I don't have it..
> 
> Just try to make your screen size smaller in browser, it happend for me for the screens less than 500px or smth

I don't have this bug with all mobile and full screen sizes... I fix the pointer under the tooltip

2024-11-29 11:47 UTC, whateverfw commented
@Thibrac  ![image](https://github.com/user-attachments/assets/6afb97e8-6d8e-45d0-8494-bfad11a954b1)

Still broken, starting from 390 (Iphone 12 Pro example) till 768

2024-11-29 11:48 UTC, whateverfw requested changes
⏫

2024-11-29 12:28 UTC, Thibrac commented
> @Thibrac ![image](https://private-user-images.githubusercontent.com/40571528/391074395-6afb97e8-6d8e-45d0-8494-bfad11a954b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4ODMzMTEsIm5iZiI6MTczMjg4MzAxMSwicGF0aCI6Ii80MDU3MTUyOC8zOTEwNzQzOTUtNmFmYjk3ZTgtNmQ4ZS00NWQwLTg0OTQtYmZhZDExYTk1NGIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDEyMjMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwYWNjMWU5OTk0ODM3MjZjNTgyOWZhNTBmODdiMzhhZDgwYjA3YzMyNWRhYzc5NDgwMTIxZWE3NmUzZTAxNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JeDdc7E6oRkVxTgQuoXOVZ6h3Ryq5FaeYYDYSTGTKTk)
> 
> Still broken, starting from 390 (Iphone 12 Pro example) till 768

Sorry but i don't have this problem on Chrome, I'll try it on another browser.

![Capture d’écran 2024-11-28 221036](https://github.com/user-attachments/assets/b95d155a-ab1b-47b6-91c9-595a997cee62)

2024-11-29 12:56 UTC, whateverfw commented
@Thibrac Not sure, I got this on chrome, anyways, If you will make this tooltip of size just line in figma 36x32 (which is not correctly in the app) and also consider paddings -  it should fit

2024-11-29 15:16 UTC, whateverfw requested changes
@Thibrac tooltip size stil doesn't correspond to figma.  (that's why it keeps breaking into multiple lines)

2024-11-29 15:36 UTC, Thibrac commented
> @Thibrac tooltip size stil doesn't correspond to figma. (that's why it keeps breaking into multiple lines)

I'm fixing this sorry for the time

2024-11-29 16:02 UTC, whateverfw approved these changes

2024-11-29 16:08 UTC, djeck1432 approved these changes
Looks good to me

2024-11-29 16:08 UTC, merged