in progress
djeck1432/spotnet pull request #306
Opened 2024-11-29 10:01 UTC by gregemax

rounding up with [FRontend] Vault Stake page [mobile] #304

2024-11-29 11:39 UTC, djeck1432 commented
@gregemax Please, you ran out of time, so please, finish it right away, we will merge everyting in 12 hours. Don't hesitate.
if there is no finish PR in an hour, you will be unassigned

2024-11-29 12:01 UTC, whateverfw requested changes

2024-11-29 12:01 UTC, whateverfw commented on frontend/src/pages/vault/stake/Stake.jsx
Also on desktop card seems not to be visible as in Figma, not sure if that was done by your changes but  could you also fix that 
![image](https://github.com/user-attachments/assets/e84d27ef-ae62-4e98-ad83-4b3d0520cab1)

2024-11-29 12:25 UTC, gregemax commented
Noted. I'll be on it

2024-11-29 13:55 UTC, djeck1432 commented
@gregemax Please, we don't have a lot of time, fix it immediately

2024-11-29 15:14 UTC, whateverfw commented
@gregemax 
1) everything is duplicated on a page
2) fix CI
3) starknet icon in options now broken
4) top cards broken on mobile, but should've fit screen
![image](https://github.com/user-attachments/assets/dd0fccc2-bce9-4297-96a7-5d6834720774)

2024-11-29 15:15 UTC, djeck1432 commented
@gregemax please, fix also test cases

2024-11-29 16:21 UTC, whateverfw requested changes
@gregemax 
1) desktop version is now broken, fix it according to figma
__
still unresolved after last commit:
2) starknet icon in options now broken
3) top cards broken on mobile, but should've fit screen

2024-11-29 17:10 UTC, djeck1432 commented
@gregemax please, fix your issues as soon as possible

2024-11-29 17:58 UTC, djeck1432 commented
@gregemax as far as vault will be in next release, you will have more time, but please, remember about 12hours update, if there is any update during 12 hours from your side, you will be unassigned

2024-11-29 21:54 UTC, whateverfw commented
<img width="554" alt="image" src="https://github.com/user-attachments/assets/d3701f8f-8661-4a8c-a220-eb19207a3dbc">
1) still broken on <768px devices
2) also page bg don't correspond to figma
3) main content doesn't have borders on desktop, but has on mobile, please fix as well
<img width="1127" alt="image" src="https://github.com/user-attachments/assets/d48f13d5-47df-4ba2-8544-ff989091dd63">


@gregemax

2024-11-29 21:55 UTC, whateverfw requested changes
@gregemax ⏫

2024-11-30 11:16 UTC, whateverfw requested changes
desktop version is broken now, it should be accroding to figma...

![Uploading image.png…]()

2024-11-30 11:18 UTC, whateverfw requested changes
1) You can clearly see that 2 cards fit 390 screen in figma but not in the app....
<img width="540" alt="image" src="https://github.com/user-attachments/assets/cbaa9964-d8a8-4892-ac00-c80c0c78a331">

2) Also starknet icon is not displayed on mobile (inside a top-card)

3) I can't open a dropdown, it should be opened whenever I click any area if a selector

2024-11-30 11:32 UTC, whateverfw commented
@gregemax resolve conflicts with main, and make sure it doesn't break withdraw page as well

2024-11-30 12:41 UTC, whateverfw commented
@gregemax please fix failed build and comments above.

2024-11-30 14:39 UTC, whateverfw requested changes
Withdraw page completely dissapeared on mobile after the merge with main, probably you merged it wrong.
<img width="728" alt="image" src="https://github.com/user-attachments/assets/1d59aca4-e8cb-486a-994e-9186d187715b">

2024-11-30 14:40 UTC, whateverfw requested changes
<img width="451" alt="image" src="https://github.com/user-attachments/assets/6a91c56f-7b02-443a-a367-133c8cb1b6f4">
stake page is also not completely working well.

2024-11-30 16:38 UTC, whateverfw commented
@gregemax any updates?

2024-11-30 16:40 UTC, gregemax commented
working on it

2024-11-30 19:57 UTC, djeck1432 commented
@gregemax any updates?

2024-11-30 21:27 UTC, whateverfw requested changes
1)

2024-11-30 21:27 UTC, whateverfw commented on frontend/src/pages/vault/stake/Stake.jsx
> +    { icon: <Image src={STRKIMG} />, title: 'STRK', balance: '0.046731' },
use it just like other components

2024-11-30 21:27 UTC, whateverfw commented on frontend/src/pages/vault/stake/stake.css
> +/* here */
remove comment

2024-11-30 21:27 UTC, whateverfw commented on frontend/src/pages/vault/stake/stake.css
> +  } */
remove comment

2024-11-30 21:27 UTC, whateverfw commented on frontend/src/pages/vault/stake/stake.css
> + */
remove commented code

2024-11-30 21:27 UTC, whateverfw commented on frontend/src/pages/vault/stake/stake.css
page background still do not correpond to figma.

2024-12-01 09:03 UTC, gregemax commented on frontend/src/pages/vault/stake/Stake.jsx
>                <div className="network-selector">
Hello @whateverfw  
The network selector issue was present when I pulled the code from the main branch, so I believe it's not from my changes. I commented out the previous and put in this new change  , 
// const handleChange = (e) => {
  //   setSelectedNetwork(e.target.value);
  // };
  const handleChange = (network) => {
    setSelectedNetwork(network.name);
  };
but I’m not sure if that resolves the problem.
and again why the network selector 
Hover Removed: Mobile devices don't support hover, so  I will use click event.

2024-12-01 09:12 UTC, whateverfw commented on frontend/src/pages/vault/stake/stake.css
you can clearly see, even in colors, that bg is still not the same as in figma

2024-12-01 09:13 UTC, whateverfw commented on frontend/src/pages/vault/stake/stake.css
<img width="525" alt="image" src="https://github.com/user-attachments/assets/f7179c1e-f078-4eb1-b8bd-b0de9b314933">
mobile is broken and don't look like in figma

2024-12-01 09:14 UTC, whateverfw commented on frontend/src/pages/vault/stake/Stake.jsx
>                <div className="network-selector">
I understand, but obviously when you merge something in your branch, you should do it properly and verify that everything works, correctly. So yeah, now it works no mobile, thanks, but remove commented code, it is redundant to leave.

2024-12-01 09:14 UTC, whateverfw requested changes

2024-12-01 09:14 UTC, whateverfw commented on frontend/src/pages/vault/stake/Stake.jsx
Also, please format your file, thanks

2024-12-01 10:53 UTC, whateverfw commented on frontend/src/pages/vault/stake/Stake.jsx
>                <div className="network-selector">
@gregemax

2024-12-01 10:54 UTC, whateverfw commented on frontend/src/pages/vault/stake/stake.css
@gregemax

2024-12-01 14:22 UTC, whateverfw requested changes
![image](https://github.com/user-attachments/assets/5fd805ed-6adf-4618-b956-5e23c6d9bc72)

Padding from right and left is not equal, I can clearly see it..

Top cards sizes do not correspond to figma.

2024-12-01 14:23 UTC, whateverfw requested changes
broken 
![image](https://github.com/user-attachments/assets/c88a0b58-8bc7-4047-a028-6a7f17d71d6f)

2024-12-01 14:23 UTC, whateverfw requested changes
broken
![image](https://github.com/user-attachments/assets/7efa650a-2e87-4ccd-b081-88b10d8083a5)

2024-12-01 16:29 UTC, whateverfw commented
@gregemax can you please test your changes before your commits and tag me only when you verify by yourself that bugs are fixed?

everything is still broken what was mentioned above, the only thing is mobile paddings and sizes had been improved, but now another thing is broken like that.
![image](https://github.com/user-attachments/assets/1e092b58-eafa-4392-8f3b-3ceb55c415de)

2024-12-01 16:38 UTC, djeck1432 commented
@gregemax are you sure you can manage it,I see every next commit you have new issue?

2024-12-02 11:11 UTC, gregemax commented
Hello  @whateverfw  are you available for a Google meet  ? please  
Thanks

2024-12-02 12:27 UTC, whateverfw commented
> Hello @whateverfw are you available for a Google meet ? please Thanks

@gregemax You can write your questions here.

2024-12-02 12:44 UTC, djeck1432 approved these changes
Partially done work,

2024-12-02 12:44 UTC, merged