feat: make vault withdraw page mobile resp.
djeck1432/spotnet pull request #308
Opened 2024-11-29 21:24 UTC by Oshioke-Salaki

fixes #295

Made withdraw vault page responsive on mobile screens.

2024-11-29 21:51 UTC, whateverfw requested changes

2024-11-29 21:51 UTC, whateverfw commented on frontend/src/components/MetricCard/metricCard.css
> +  .metric-card {
inner padding and title's font-size are not the same as in figma

2024-11-29 21:51 UTC, whateverfw commented on frontend/src/pages/vault/withdraw/withdraw.css
> +    border-bottom: 1px #201338 solid;
top cards seems to have padding from sides, not like in figma

2024-11-29 21:51 UTC, whateverfw commented on frontend/src/pages/vault/withdraw/withdraw.css
can you please check and fix page's background, because currently it seems to differ from figma a lot, thanks

2024-11-29 21:51 UTC, whateverfw commented on frontend/src/pages/vault/withdraw/withdraw.css
<img width="714" alt="image" src="https://github.com/user-attachments/assets/d533f71d-5a87-490f-9d26-de5938139ca5">
cards and bg is broken on tablet's screen sizes (<768px) till mobile

2024-11-30 08:20 UTC, whateverfw commented on frontend/src/components/MetricCard/metricCard.css
> +  .metric-card {
I believe paddings are still incorrect, because in figma this card has smaller height (of 88px)

2024-11-30 08:23 UTC, whateverfw requested changes
Can you make sure that content is inside a card with border just like in Figma, currently desktop version doesn't correspond to Figma
<img width="955" alt="image" src="https://github.com/user-attachments/assets/eeffd4fe-2654-4a05-bcec-193dc2096d9a">
Figma:
<img width="511" alt="image" src="https://github.com/user-attachments/assets/a990826f-3410-4a38-9475-f3e4301bb42b">

Not sure if that's particularly because of mobile changes, but please fix this as well, thanks!

2024-11-30 11:23 UTC, whateverfw approved these changes
lgtm

2024-11-30 11:31 UTC, djeck1432 approved these changes
Good job, looks good to me

2024-11-30 11:31 UTC, merged