feat: add_extra_deposit method
djeck1432/spotnet pull request #365
Opened 2024-12-13 17:40 UTC by ooochoche

Fixes #352

2024-12-13 20:36 UTC, djeck1432 commented
@ooochoche this code could be made for 2 mins, where is the rest? in the morning this task should be done otherwise you will be unassigned

2024-12-13 20:37 UTC, djeck1432 requested changes
bad work, finalize it within next 12hours.

2024-12-14 11:06 UTC, djeck1432 requested changes

2024-12-14 11:06 UTC, djeck1432 commented on web_app/api/position.py
> +
add checking also `amount`

2024-12-14 11:07 UTC, ooochoche commented on web_app/api/position.py
> +
Alright

2024-12-14 20:30 UTC, djeck1432 requested changes
Please, add one condition and I will merge it

2024-12-14 20:45 UTC, ooochoche commented
I am currently on it

2024-12-14 21:30 UTC, ooochoche commented
@djeck1432 done!

2024-12-15 13:52 UTC, djeck1432 approved these changes
Looks good to me

2024-12-15 13:53 UTC, merged