feat: add history page, implement usePosition hook to fetch table data
djeck1432/spotnet pull request #393
Opened 2024-12-17 11:24 UTC by Ibinola

2024-12-18 11:06 UTC, whateverfw commented
@Ibinola any updates?

2024-12-18 11:06 UTC, djeck1432 commented
@Ibinola Any updates?

2024-12-18 11:52 UTC, Ibinola commented
pushed recent updates

> @Ibinola any updates?

2024-12-18 12:39 UTC, whateverfw requested changes

2024-12-18 12:39 UTC, whateverfw commented on frontend/src/pages/spotnet/position_history/position_history.css
please use camelCase, not snake_case

2024-12-18 12:39 UTC, whateverfw commented on frontend/src/hooks/usePosition.js
name this usePositionHistory, please

2024-12-18 12:39 UTC, whateverfw commented on frontend/src/hooks/usePosition.js
> +const usePositionHistoryTable = (walletId) => {
you can access walletId directly from store here, not passing from a component

2024-12-18 12:39 UTC, whateverfw commented on frontend/src/hooks/usePosition.js
> +export { fetchPositionHistoryTable, usePositionHistoryTable };
seems to be unnecessary to export fetchPositionHistoryTable

2024-12-18 12:39 UTC, whateverfw commented on frontend/src/pages/spotnet/position_history/PositionHistory.jsx
> +    data: { health_ratio: '1.5', current_sum: '0.05', start_sum: '0.04', borrowed: '10.0' },
remove this defaults

2024-12-18 12:39 UTC, whateverfw commented on frontend/src/pages/spotnet/position_history/PositionHistory.jsx
> +  const [borrowed, setBorrowed] = React.useState('0.00');
you don't need useState and useEffect for these values, you should use it directly returned from `useDashboardData` hook

2024-12-18 12:39 UTC, whateverfw commented on frontend/src/pages/spotnet/position_history/PositionHistory.jsx
> +  }, [walletId, data, tableData, isLoading]);
you don't need useEffect you should use it directly returned from useDashboardData hook

2024-12-18 12:39 UTC, whateverfw commented on frontend/src/pages/spotnet/position_history/PositionHistory.jsx
> +            <Card label="Borrow Balance" cardData={borrowed} icon={<EthIcon className="icon" />} />
please make sure styles are the same as in figma (currently it is not). So please modify this Card component to look like in figma, also currently on mobile (390px at least) cards are split into two lines, but it should fit one

2024-12-18 12:39 UTC, whateverfw commented on frontend/src/pages/spotnet/position_history/PositionHistory.jsx
> +  const { data: tableData, isLoading } = usePositionHistoryTable(walletId);
'isLoading` doesn't exist in `useQuery` API - in order to check loading state it has `isPending`, please change and make sure loading works.

2024-12-18 12:39 UTC, whateverfw commented on frontend/src/pages/spotnet/position_history/PositionHistory.jsx
> +                        <span className="action-button" onClick={() => setSelectedPosition(data)}>
action button should be present only in mobile version

2024-12-18 12:39 UTC, whateverfw commented on frontend/src/pages/spotnet/position_history/PositionHistory.jsx
> +                  {tableData?.map((data, index) => (
please provide some message in case tableData is empty and there are not opened positions

2024-12-18 12:39 UTC, whateverfw commented on frontend/src/pages/spotnet/position_history/PositionHistory.jsx
there should be no scroll on mobile, please check styles, it should fit correctly, also there should be an icon above actions in mobile design (in th). Please check figma.
![image](https://github.com/user-attachments/assets/731c31d2-3c9a-467c-83ed-032ea04a4d7c)

2024-12-18 12:39 UTC, whateverfw commented on frontend/src/pages/spotnet/position_history/PositionHistory.jsx
> +          <div className="position-table-title">
should be centered on mobile, also has different font weight in figma

2024-12-18 12:39 UTC, whateverfw commented on frontend/src/utils/formatDate.js
please use more cleaner solution, using native browser API, such as:

```
export function formatDate(timestamp) {
    const date = new Date(timestamp);
    return new Intl.DateTimeFormat('en-GB', {
        day: '2-digit',
        month: '2-digit',
        year: '2-digit',
        hour: '2-digit',
        minute: '2-digit',
        hour12: true
    }).format(date).replace(',', ' -');
}
```

2024-12-18 12:39 UTC, whateverfw commented on frontend/src/pages/spotnet/position_history/position_history.css
> +}
is it necessary here? seems like we have it in `globals.css`, please remove

2024-12-18 12:39 UTC, whateverfw commented on frontend/src/pages/spotnet/position_history/PositionHistoryModal.jsx
you already formatting those values in position history table  in order to display on desktop view,
 I'd suggest to have map through those values, returned from a backend, and format it one time at the starting point in one place and then use it both in table in here. It can be done using `useQuery`'s `select` property, so data will be correctly transfromed return, right away when returned from a custom usePositionHistory hook.

2024-12-18 20:00 UTC, djeck1432 commented
@Ibinola Any updates?

2024-12-18 20:45 UTC, whateverfw commented
@Ibinola please sync with `main` and resolve merge conflicts

2024-12-19 08:24 UTC, whateverfw approved these changes
@Ibinola 
looks good to me, well done

2024-12-19 09:09 UTC, djeck1432 approved these changes
looks good to me

2024-12-19 09:09 UTC, merged