Fix stake page UI  desktop/mobile
djeck1432/spotnet pull request #400
Opened 2024-12-17 20:59 UTC by ONEONUORA

2024-12-17 21:41 UTC, whateverfw requested changes

2024-12-17 21:41 UTC, whateverfw commented on frontend/public/background(jpeg).png
seems like there are already existing background file.

2024-12-17 21:41 UTC, whateverfw commented on frontend/src/pages/vault/stake/stake.css
remove commented code

2024-12-17 21:41 UTC, whateverfw commented on frontend/src/pages/vault/stake/stake.css
this mobile part is broken  
<img width="443" alt="image" src="https://github.com/user-attachments/assets/fe4c5b61-9329-4442-a802-44ddfe983a4c" />

2024-12-17 21:41 UTC, whateverfw commented on frontend/src/pages/vault/vaultLayout.css
remove commented code

2024-12-17 21:41 UTC, whateverfw commented on frontend/src/pages/vault/stake/stake.css
remove commented code

2024-12-17 21:56 UTC, ONEONUORA commented
Okay working on it

2024-12-18 14:41 UTC, whateverfw requested changes
everything seems to be OK now, both deskop and mobile, please fix tablet:

![image](https://github.com/user-attachments/assets/e51b840b-4338-4ef7-9448-cb2873ef5791)

2024-12-18 14:41 UTC, whateverfw commented on frontend/public/background(jpeg).png
please use existing background file, delete this

2024-12-18 15:15 UTC, ONEONUORA commented
Pls can you point to right image name

2024-12-18 15:28 UTC, whateverfw commented
@ONEONUORA 
> Pls can you point to right image name

https://github.com/djeck1432/spotnet/blob/main/frontend/public/background.png
it was already used on this page

2024-12-18 20:28 UTC, whateverfw commented
@ONEONUORA any updates?

2024-12-18 20:32 UTC, ONEONUORA commented
@whateverfw Pls i need more time, I am refactoring the code to fix the tablet

2024-12-19 08:27 UTC, whateverfw approved these changes
lgtm

2024-12-19 09:10 UTC, djeck1432 approved these changes
Looks good to me

2024-12-19 09:10 UTC, merged