Feat: Add pagination to position history endpoint
djeck1432/spotnet pull request #401
Opened 2024-12-17 22:34 UTC by KeneePatel

Changes include:
- Constant of PAGINATION_STEP is added with the value of 10
- `get_user_positions` function endpoint now has an optional `start` argument for accepting query parameter of `start`
- `get_positions_by_wallet_id` db function now accepts `start`, and `limit` parameters to accommodate the change

No breaking changes

Modification to a functionality is done and was to be expected due to the nature of issue.

2024-12-17 22:41 UTC, KeneePatel commented
Ahh the good old failing tests. Will have to refactor them for the modified changes. I will take some time for those.

2024-12-17 22:52 UTC, KeneePatel commented
Some guidance on how I should approach for the tests to pass will be appreciated. I am still a bit ambiguous on how I should tackle the test cases.

I can try to modify the functions so they integrate well the existing test cases, or refactor the test cases to accommodate the functional changes? Please tell me which route would be a better option.

2024-12-18 10:52 UTC, djeck1432 requested changes
Regarding test cases, you can adjust them based on your changes

2024-12-18 10:52 UTC, djeck1432 commented on web_app/api/position.py
> +    if start is not None:
```
   if start is not None:
   start_index = max(0, start)
    else:
        start_index = 0
```
this all code can be done in one line: 
start_index = start and max(0, start) or 0

2024-12-18 15:33 UTC, djeck1432 commented
@KeneePatel Any updates,
please also fix test cases

2024-12-18 20:04 UTC, djeck1432 commented
@KeneePatel Any updates? Just friendly reminder that if you don't update PR you can be unassigned

2024-12-18 20:08 UTC, KeneePatel commented
It was busy today. I will update the PR in 6 hours.

2024-12-18 20:10 UTC, djeck1432 commented
@KeneePatel okay, thank you for update

2024-12-19 07:06 UTC, djeck1432 approved these changes
Looks good to me

2024-12-19 07:06 UTC, merged