Add new page add_deposit
djeck1432/spotnet pull request #410
Opened 2024-12-19 13:54 UTC by GoSTEAN

2024-12-19 20:44 UTC, whateverfw requested changes

2024-12-19 20:44 UTC, whateverfw commented on frontend/src/App.jsx
> +          <Route path="/add_deposit" element={<Add_Deposit />} />
could you please put it under `dashboard/add-deposit` path?

2024-12-19 20:44 UTC, whateverfw commented on frontend/src/pages/spotnet/dashboard/add_deposit.jsx
you should have `add-deposit` folder inside `dashboard`, with `AddDeposit.jsx` and `addDeposit.css`, rename/rework

2024-12-19 20:44 UTC, whateverfw commented on frontend/src/pages/spotnet/dashboard/add_deposit.jsx
> +    const regex = /^\d*\.?\d*$/;
please extract this to a `utils/regex.js` folder and name as a constant with an uppercase with more meaningful name, like `NUMBER_REGEX` or smth

2024-12-19 20:44 UTC, whateverfw commented on frontend/src/pages/spotnet/dashboard/add_deposit.css
> +  }
we already have this in global.css, remove

2024-12-19 20:44 UTC, whateverfw commented on frontend/src/pages/spotnet/dashboard/add_deposit.jsx
please run `yarn format` in order to format your files with prettier

2024-12-19 20:44 UTC, whateverfw commented on frontend/src/pages/spotnet/dashboard/add_deposit.jsx
> +        <button className=" withdraw-button btn">Deposit</button>
currently it is not integrated with a backend, as requested in an issues. Please create custom hook `useAddDeposit` and perform actions using `useMutation` hook of `tanstack-query`, as stated in the issue, `position_id` will be returned from `useDashboardData` hook, so take it from there in order to make add deposit request.

2024-12-19 20:44 UTC, whateverfw commented on frontend/src/pages/spotnet/dashboard/add_deposit.jsx
> +            <Card label="Borrow Balance" value="$-55.832665" icon={<EthIcon className="icon" />} />
cards do not look like in figma, everything is different, pleae make changes to css and verify it looks just like in figma on both mobile and desktop

2024-12-19 20:44 UTC, whateverfw commented on frontend/src/components/TokenSelector/TokenSelector.jsx
that's good you've created sepearate folder for token selector, but please make styles according to figma, also remove duplicated `components/TokenSelector.jsx` and use this new one in `Form.jsx` as well as on deposit page (that you already do)

2024-12-19 20:44 UTC, whateverfw commented on frontend/src/components/TokenSelector/TokenSelector.css
please name your classess correctly, most likely with `token` prefix, it should not have anything related to form in the name. Also css completely do not match figma on mobile/desktop. Please fix

2024-12-19 20:44 UTC, whateverfw commented on frontend/src/pages/spotnet/dashboard/add_deposit.jsx
> +              </div>
please fix styles for this input, currently it do not match figma, font is too small and

2024-12-19 20:44 UTC, whateverfw commented on frontend/src/pages/spotnet/dashboard/add_deposit.css
> +    } */
do not keep commented code

2024-12-20 20:00 UTC, whateverfw requested changes
How is the progress with a tasks?

2024-12-20 20:00 UTC, whateverfw commented on frontend/src/components/TokenSelector.jsx
you should work only with single `TokenSelector`, please remove this one and work/use only your newly created TokenSelector.jsx

2024-12-20 20:51 UTC, GoSTEAN commented on frontend/src/components/TokenSelector.jsx
Okay, working on it 
Will be done soon

2024-12-21 07:41 UTC, djeck1432 commented
@GoSTEAN Any updates?
all PR should be merged today, if you not finish your task you will be rewarded partially

2024-12-21 08:14 UTC, whateverfw commented
@GoSTEAN sync with main and fix merge conflicts

2024-12-21 09:07 UTC, GoSTEAN commented
Presently fixing the conflicts , Will be pushing soon

2024-12-21 10:28 UTC, GoSTEAN commented
@whateverfw I have resolved the conflict on my local machine but it's still reflecting on Github. Pls what should i do ?

2024-12-21 10:43 UTC, whateverfw commented
@GoSTEAN I'm not sure, did you resolve it correctly and pushed the changes to git?

2024-12-21 12:33 UTC, djeck1432 commented
@GoSTEAN To save time, open new open, but do NOT close this one

2024-12-21 14:51 UTC, GoSTEAN commented
@djeck1432 I have created a new pull request

2024-12-22 07:31 UTC, djeck1432 commented
Close this PR as a duplicated

2024-12-22 07:31 UTC, closed without merging