adding the reusable sidebar
djeck1432/spotnet pull request #411
Opened 2024-12-19 14:08 UTC by Dprof-in-tech

closes #407

2024-12-20 19:48 UTC, whateverfw commented
@Dprof-in-tech seems like it is not finished yet?  or can I review already?

2024-12-20 19:56 UTC, Dprof-in-tech commented
Please give me a couple of minutes so I can push the remaining updates .
I’ll send you a telegram dm once I do that.

On Fri, Dec 20, 2024 at 8:48 PM whateverfw ***@***.***> wrote:

> @Dprof-in-tech <https://github.com/Dprof-in-tech> seems like it is not
> finished yet? or can I review already?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/djeck1432/spotnet/pull/411#issuecomment-2557627748>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3W3TPL4OXVBVTIFTM62TTT2GRYBLAVCNFSM6AAAAABT5CIQVOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNJXGYZDONZUHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-12-21 08:28 UTC, whateverfw requested changes
@Dprof-in-tech Please resolve comments
Also sync with main. Notice that there were changes to folder structure and file's locations. Please merge it to your branch and make sure your changes is not overriden and applied correctly

2024-12-21 08:28 UTC, whateverfw commented on frontend/src/pages/spotnet/dashboard/Dashboard.jsx
> +      <Sidebar title={'Dashboard'} items={dashboardItems} className="sidebar-docs-sticky" />
dashboard should not have title (just like in figma)

2024-12-21 08:28 UTC, whateverfw commented on frontend/src/pages/spotnet/documentation/Documentation.jsx
> +      {/* <TableOfContents tabelTitle={"Table Of Content"} defaultActiveId={"introduction"} headerHeight={80} items={tableOfContents} /> */}
please remove commented parts

2024-12-21 08:28 UTC, whateverfw commented on frontend/src/components/ui/Components/Sidebar/Sidebar.css
item's color do not match figma, should be `#83919F` in default state and `#F0F0F0` in active state

also please make sure left padding and vertical padding between items are according to figma

2024-12-21 08:28 UTC, whateverfw commented on frontend/src/pages/vault/VaultLayout.jsx
> +      {/* <aside className="sidebar">
remove commented code

2024-12-21 08:28 UTC, whateverfw commented on frontend/src/pages/vault/VaultLayout.jsx
> +      icon: '•'
<img width="372" alt="image" src="https://github.com/user-attachments/assets/419c609d-e1ab-4f8a-8a55-4ee2beb0d143" />

Also, title styles do not match Figma

2024-12-21 08:28 UTC, whateverfw commented on frontend/src/pages/spotnet/documentation/Documentation.jsx
>    const tableOfContents = [
<img width="372" alt="image" src="https://github.com/user-attachments/assets/57a86e8f-a9a2-46cc-ab51-ee9ee9e20df7" />

- Icorrect title styles
- no icons near the items and seems like sub-items do not work correctly
- when clicking `Overview` I can't select any other item anymore
- when I click getting started, all items below is highlighted, also those items can't be directly selected

2024-12-21 09:12 UTC, Dprof-in-tech commented
I’m on it chief

On Sat, Dec 21, 2024 at 9:29 AM whateverfw ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> @Dprof-in-tech <https://github.com/Dprof-in-tech> Please resolve comments
> Also sync with main. Notice that there were changes to folder structure
> and file's locations. Please merge it to your branch and make sure your
> changes is not overriden and applied correctly
> ------------------------------
>
> In frontend/src/pages/spotnet/dashboard/Dashboard.jsx
> <https://github.com/djeck1432/spotnet/pull/411#discussion_r1894583492>:
>
> > -                  <span className="tab-title">Collateral & Earnings</span>
> -                </button>
> -
> -                <div className="tab-divider" />
> -
> -                <button
> -                  onClick={() => setIsCollateralActive(false)}
> -                  className={`tab ${!isCollateralActive ? 'active borrow' : ''}`}
> -                >
> -                  <BorrowIcon className="tab-icon" />
> -                  <span className="tab-title">Borrow</span>
> -                </button>
> -                <div className="tab-indicator-container">
> -                  <div className={`tab-indicator ${isCollateralActive ? 'collateral' : 'borrow'}`} />
> +    <div className="dashboard">
> +      <Sidebar title={'Dashboard'} items={dashboardItems} className="sidebar-docs-sticky" />
>
> dashboard should not have title (just like in figma)
> ------------------------------
>
> In frontend/src/pages/spotnet/documentation/Documentation.jsx
> <https://github.com/djeck1432/spotnet/pull/411#discussion_r1894583545>:
>
> > @@ -89,7 +91,8 @@ const Documentation = () => {
>
>    return (
>      <div className="documentation-page">
> -      <TableOfContents tabelTitle={"Table Of Content"} defaultActiveId={"introduction"} headerHeight={80} items={tableOfContents} />
> +      {/* <TableOfContents tabelTitle={"Table Of Content"} defaultActiveId={"introduction"} headerHeight={80} items={tableOfContents} /> */}
>
> please remove commented parts
> ------------------------------
>
> On frontend/src/components/ui/Components/Sidebar/Sidebar.css
> <https://github.com/djeck1432/spotnet/pull/411#discussion_r1894583710>:
>
> item's color do not match figma, should be #83919F in default state and
> #F0F0F0 in active state
>
> also please make sure left padding and vertical padding between items are
> according to figma
> ------------------------------
>
> In frontend/src/pages/vault/VaultLayout.jsx
> <https://github.com/djeck1432/spotnet/pull/411#discussion_r1894583763>:
>
> >    return (
>      <div className="layout">
> -      <aside className="sidebar">
> +      {/* <aside className="sidebar">
>
> remove commented code
> ------------------------------
>
> In frontend/src/pages/vault/VaultLayout.jsx
> <https://github.com/djeck1432/spotnet/pull/411#discussion_r1894583830>:
>
> >
>  export function VaultLayout({ children }) {
> +  const vaultItems = [
> +    {
> +      id: 'home',
> +      name: 'Home',
> +      link: '/',
> +      icon: '•'
>
> image.png (view on web)
> <https://github.com/user-attachments/assets/419c609d-e1ab-4f8a-8a55-4ee2beb0d143>
>
> Also, title styles do not match Figma
> ------------------------------
>
> In frontend/src/pages/spotnet/documentation/Documentation.jsx
> <https://github.com/djeck1432/spotnet/pull/411#discussion_r1894584403>:
>
> > @@ -12,9 +13,10 @@ const Documentation = () => {
>
>
>    const tableOfContents = [
>
> image.png (view on web)
> <https://github.com/user-attachments/assets/57a86e8f-a9a2-46cc-ab51-ee9ee9e20df7>
>
>    - Icorrect title styles
>    - no icons near the items and seems like sub-items do not work
>    correctly
>    - when clicking Overview I can't select any other item anymore
>    - when I click getting started, all items below is highlighted, also
>    those items can't be directly selected
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/djeck1432/spotnet/pull/411#pullrequestreview-2518610079>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3W3TPM656XLU74MYFZXL5L2GURE7AVCNFSM6AAAAABT5CIQVOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMJYGYYTAMBXHE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-12-21 20:43 UTC, djeck1432 commented
@Dprof-in-tech Please, resolve conflict

2024-12-22 06:56 UTC, Dprof-in-tech commented
fixed ser

2024-12-22 07:34 UTC, djeck1432 commented
@Dprof-in-tech Please, fix test cases

2024-12-22 11:23 UTC, whateverfw requested changes
please fix ci issues and resolve earlier mentioned comments

2024-12-22 11:23 UTC, whateverfw commented on frontend/src/components/ui/Components/Sidebar/Sidebar.jsx
it should be located in `components/ui/sidebar` folder, as well as css file

2024-12-22 12:20 UTC, djeck1432 approved these changes
Partially reward, as far task is not finished

2024-12-22 12:20 UTC, merged