feat: centralize background image handling and clean up assets
djeck1432/spotnet pull request #420
Opened 2024-12-20 20:46 UTC by BigBen-7

2024-12-21 08:09 UTC, whateverfw requested changes
Individual pages should not have bg files, it should only be set in a wrapper (.App) once - for desktop and mobile.

Remove background from all other .css files, along with image assets that should not be used anymore

2024-12-21 08:11 UTC, whateverfw commented
@BigBen-7 Also please remove merge conflicts (I believe you can accept all changes from main and then remove background in those css)

2024-12-21 12:32 UTC, djeck1432 commented
@BigBen-7 Please, resolve conflict

2024-12-21 16:02 UTC, whateverfw requested changes

2024-12-21 16:02 UTC, whateverfw commented on frontend/src/globals.css
mobile background also should be here and removed from individual pages.

2024-12-21 18:27 UTC, whateverfw commented
> Individual pages should not have bg files, it should only be set in a wrapper (.App) once - for desktop and mobile.
> 
> Remove background from all other .css files, along with image assets that should not be used anymore

@BigBen-7 it is still not resolved, I don't see old background files to be removed, and background still exists on page levels

2024-12-21 21:57 UTC, whateverfw requested changes

2024-12-21 21:57 UTC, whateverfw commented on frontend/src/globals.css
> +  .withdrawall-wrapper {
why this applied to withdrawall-wrapper? 
please fix and test next time before pushing, thanks

2024-12-22 07:55 UTC, whateverfw approved these changes
lgtm

2024-12-22 08:28 UTC, djeck1432 approved these changes
looks good to me

2024-12-22 08:28 UTC, merged