updates for frontend wallet connection
djeck1432/spotnet pull request #439
Opened 2024-12-24 07:45 UTC by Nityam573

2024-12-24 12:17 UTC, iamnovichek commented
@Nityam573 make sure all pipelines are green

2024-12-25 05:00 UTC, Nityam573 commented
@iamnovichek  all pipelines are green please check

2024-12-25 10:59 UTC, iamnovichek commented
@Nityam573 What is the issue you are assigned to? I cannot find it.

2024-12-25 11:07 UTC, Nityam573 commented
@iamnovichek I wasn't assigned to any but was able to resolve this one

2024-12-25 11:13 UTC, iamnovichek commented
@Nityam573 Did you talk about that with @djeck1432 ?

2024-12-26 20:58 UTC, iamnovichek requested changes
GJ

2024-12-26 20:58 UTC, iamnovichek commented on frontend/src/services/wallet.js
> +      // connectors: [
Do we need this commented code here?

2024-12-27 03:44 UTC, Nityam573 commented on frontend/src/services/wallet.js
> +      // connectors: [
Nope not needed

2024-12-27 03:51 UTC, Nityam573 commented
@iamnovichek review please

2024-12-27 03:52 UTC, Nityam573 commented on frontend/src/services/wallet.js
> +      // connectors: [
I removed it

2024-12-27 09:56 UTC, merged