Add pre-commit hook for pylint with specific rules
djeck1432/spotnet pull request #441
Opened 2024-12-24 12:14 UTC by 1nonlypiece

closes #431

2024-12-24 12:23 UTC, 1nonlypiece commented
@iamnovichek  I've added the pre-commit configuration file, but the tool isn't installed yet, and the pre-commit install command still needs to be run to apply it. Should this be part of the task?

2024-12-24 12:24 UTC, 1nonlypiece commented
Should this setup be handled using Poetry and Docker? If so, we could limit pre-commit usage to Docker containers, but most contributors will likely commit from their local machines. What are your suggestions @iamnovichek ?

2024-12-24 14:58 UTC, iamnovichek commented
> Should this be part of the task?

@1nonlypiece yeah, please do it as well

2024-12-24 15:11 UTC, iamnovichek commented
> Should this setup be handled using Poetry and Docker? If so, we could limit pre-commit usage to Docker containers, but most contributors will likely commit from their local machines. What are your suggestions @iamnovichek ?

I think we will require that each contributor runs `pre-commit install` command on pull our repository. So install it locally pls as well and add to `pyproject.toml`

2024-12-24 17:02 UTC, 1nonlypiece commented
@iamnovichek I have added it in `pyproject.toml` and wondering how to install it locally?

2024-12-24 17:03 UTC, 1nonlypiece commented
Can we just document to install `pre-commit` locally & run `pre-commit install` command?

2024-12-24 17:39 UTC, iamnovichek commented
> Can we just document to install `pre-commit` locally & run `pre-commit install` command?

Yep, that's exactly what I meant

2024-12-24 19:07 UTC, 1nonlypiece commented
Updated! @iamnovichek

2024-12-25 06:19 UTC, 1nonlypiece commented
This PR is ready for review @iamnovichek

2024-12-25 10:50 UTC, iamnovichek requested changes

2024-12-25 10:50 UTC, iamnovichek commented on README.md
> +   pip install pre-commit
Pls add 3 into `pip install pre-commit` to be `pip3 install pre-commit`

2024-12-25 16:05 UTC, merged