Draft PR for Add fetching price from endpoint #72
djeck1432/spotnet pull request #96
Opened 2024-10-24 15:54 UTC by Benjtalkshow

Draft PR for Add fetching price from endpoint #72

2024-10-25 07:29 UTC, djeck1432 requested changes

2024-10-25 07:29 UTC, djeck1432 commented on web_app/contract_tools/mixins/dashboard.py
> +    # [ADDED] New method to fetch current token prices
Remove this comment please

2024-10-25 07:29 UTC, djeck1432 commented on web_app/contract_tools/mixins/dashboard.py
> +        except Exception as e:
Please, be more specific with Exception which you are trying to catch

2024-10-25 12:10 UTC, djeck1432 commented
@Benjtalkshow Hi, what is the update for this task, you have a little time to finish this task, otherwise it will be unassigned

2024-10-25 12:12 UTC, Benjtalkshow commented
@Benjtalkshow 
Alright ser. 
I will make the requested changes soon. thanks

2024-10-25 12:15 UTC, djeck1432 commented
thank you, don't forget to run `pylint` command 
`pylint $(git ls-files '*.py') --disable=all --enable=C0114,C0115,C0116,C0301`
and sync with main

2024-10-25 14:19 UTC, djeck1432 commented
@Benjtalkshow this task is critical and blocking us to proceed, in 4-6 hours this task will be unassigned from you. Please take it into account

2024-10-25 14:22 UTC, Benjtalkshow commented
> @Benjtalkshow this task is critical and blocking us to proceed, in 4-6 hours this task will be unassigned from you. Please take it into account

You will see it soon @djeck1432

2024-10-25 14:26 UTC, Benjtalkshow commented
Hi @djeck1432 
Why am i getting this: `# pylint $(git ls-files '*.py') --disable=all --enable=C0114,C0115,C0116,C0301`
`/bin/sh: 1: git: not found`
`/bin/sh: 1: pylint: not found`

2024-10-25 14:37 UTC, Benjtalkshow commented
Hello @djeck1432 
You can review the code now, i am active now

2024-10-25 19:38 UTC, djeck1432 requested changes

2024-10-25 19:38 UTC, djeck1432 commented on web_app/contract_tools/mixins/dashboard.py
> +            except Exception as e:  # handle if token price parsing fails
Please, be more specific with Exception, what are you going to catch here?

2024-10-25 19:38 UTC, djeck1432 commented on web_app/contract_tools/mixins/dashboard.py
> +                        prices[symbol] = float(current_price)
Don't use float, it's not precise enough, use Decimal or string

2024-10-25 19:38 UTC, djeck1432 commented on web_app/contract_tools/mixins/dashboard.py
> +async def get_current_prices(cls) -> Dict[str, float]:
where is a 4  spaces? you have an error

2024-10-25 23:40 UTC, Benjtalkshow commented on web_app/contract_tools/mixins/dashboard.py
> +async def get_current_prices(cls) -> Dict[str, float]:
Alright ser

2024-10-26 10:06 UTC, djeck1432 commented
@Benjtalkshow Any updates, again this task is blocking other developer, please finalize it as soon as possible

2024-10-26 11:16 UTC, Benjtalkshow commented
> @Benjtalkshow Any updates, again this task is blocking other developer, please finalize it as soon as possible

Hello @djeck1432 
I updated the code already. Check Please

2024-10-26 16:19 UTC, djeck1432 approved these changes
Looks good to me

2024-10-26 20:49 UTC, merged