create endpoint for token multiplier
djeck1432/spotnet pull request #99
Opened 2024-10-24 18:32 UTC by od-hunter

@djeck1432 Kindly review the endpoint created for token multiplier.

2024-10-24 19:54 UTC, djeck1432 requested changes
Looks really good, great jobs, small issues and ready to merge

2024-10-24 19:54 UTC, djeck1432 commented on web_app/api/position.py
> +
remove blank lines

2024-10-24 19:54 UTC, djeck1432 commented on web_app/api/position.py
> +class TokenMultiplierResponse(BaseModel):
Add docstrings

2024-10-24 19:54 UTC, djeck1432 commented on web_app/api/position.py
> +    class Config:
add docstring

2024-10-24 19:54 UTC, djeck1432 commented on web_app/contract_tools/constants.py
> +
remove blank line

2024-10-25 10:54 UTC, od-hunter commented
@djeck1432 , please review

2024-10-25 13:07 UTC, djeck1432 commented
@od-hunter Please, fix pylint issues

2024-10-25 14:39 UTC, od-hunter commented
@djeck1432  please review

2024-10-25 19:53 UTC, djeck1432 approved these changes
Looks good to me, Approved

2024-10-25 19:53 UTC, merged